### ISSUE TITLE
https://interface.fh-potsdam.de/is-the-lab-open/ works https://interface.fh-potsdam.de/is-the-lab-open does not

### ISSUE THREAD

**Issue by tillnagel** [FH-Potsdam/is-the-lab-open#2]

**Comment by ff6347** [comment]
Looks like need to care more about routing

express-slash
https://www.npmjs.com/package/express-slash

**Comment by ff6347** [comment]
nope. It was the htaccess rewrite rule  
now it works.
- http://interface.fh-potsdam.de/is-the-lab-open/
- http://interface.fh-potsdam.de/is-the-lab-open
