### ISSUE TITLE
provide embeddable status badge/image

### ISSUE THREAD

**Issue by philippgeuder** [FH-Potsdam/is-the-lab-open#4]
would be nice to have a "is-the-lab-open" svg-image/badge ala http://shields.io/ for 3rd parties to embed in their site (incom/bonanza :wink: ).

**Comment by ff6347** [comment]
![](https://img.shields.io/badge/is--the--lab--open-no-blue.svg)  
![](https://img.shields.io/badge/is--the--lab--open-yes-blue.svg)

**Comment by ff6347** [comment]
Works  
![](http://interface.fh-potsdam.de/is-the-lab-open/badge.svg)
